BASE: ['']
TOOLBOX_MODE: "multi_train_and_test"

TRAIN:
  BATCH_SIZE: 8
  EPOCHS: 30
  LR: 1e-4
  MODEL_FILE_NAME: PhysLLM_multisource_example
  DATA:
    DATASET: MultiSourceRPPG
    DATA_PATH: ""
    FS: 30
    DATA_FORMAT: NDCHW
    MULTI_SOURCE:
      NUM_SOURCE: 4
      SOURCE_NAME: ["UBFC-rPPG", "PURE", "BUAA", "MMPD"]
      SOURCE_PATHS:
        UBFC-rPPG: "/path/to/ubfc"
        PURE: "/path/to/pure"
        BUAA: "/path/to/buaa"
        MMPD: "/path/to/mmpd"
    CACHED_PATH: "/path/to/preprocessed_cache"
    PREPROCESS:
      DATA_TYPE: ['Raw']
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      RESIZE:
        H: 72
        W: 72

VALID:
  DATA:
    DATASET: UBFC-rPPG
    DATA_PATH: "/path/to/ubfc"
    CACHED_PATH: "/path/to/preprocessed_cache"
    FS: 30
    DATA_FORMAT: NDCHW
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['Raw']
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      RESIZE:
        H: 72
        W: 72

TEST:
  USE_LAST_EPOCH: True
  METRICS: ['MAE', 'RMSE', 'MAPE', 'Pearson', 'SNR']
  DATA:
    DATASET: MPUZPHRPPGST
    DATA_PATH: "/path/to/zpu_or_zph_raw_data"
    CACHED_PATH: "/path/to/zpu_or_zph_cache"
    EXP_DATA_NAME: "ZPH_Chunk160_Det30"
    FS: 30
    DATA_FORMAT: NDCHW
    BEGIN: 0.6
    END: 0.8
    PREPROCESS:
      DATA_TYPE: ['Raw']
      LABEL_TYPE: Standardized
      DO_CHUNK: True
      CHUNK_LENGTH: 160
      RESIZE:
        H: 72
        W: 72

MODEL:
  NAME: PhysLLM
  VIDEO_ENC: PhysNet
  FACE_MODEL: FaceXFormer
  ENV_MODEL: clip
  LLM: BERT
  MLLM: ""
  CHECKPOINTS:
    VIDEO_ENCODER: "/path/to/video_encoder_checkpoint.pth"
    FACE_ENCODER: "/path/to/face_encoder_checkpoint.pt"

INFERENCE:
  BATCH_SIZE: 8
  EVALUATION_METHOD: FFT
  EVALUATION_WINDOW:
    USE_SMALLER_WINDOW: True
    WINDOW_SIZE: 30
